## Numpy Array Operations

In [84]:
import numpy as np

### Array Slicing

In [85]:
arr = np.arange(1,20,2)
print("Original Array : ", arr)
print("Basic Slicing : ", arr[2:7])
print("Slicing with Step : ", arr[2:7:2])
print("Negative Indexing : ", arr[-7])
print("Negative Indexing Slicing: ", arr[-7:-1])
print("Negative Indexing Slicing: ", arr[-7:-1:2])

Original Array :  [ 1  3  5  7  9 11 13 15 17 19]
Basic Slicing :  [ 5  7  9 11 13]
Slicing with Step :  [ 5  9 13]
Negative Indexing :  7
Negative Indexing Slicing:  [ 7  9 11 13 15 17]
Negative Indexing Slicing:  [ 7 11 15]


In [86]:
arr_2D = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(arr_2D)
print("Specific Element : ", arr_2D[1,2])
print("Entire Row : ", arr_2D[2])
print("Entire Row : ", arr_2D[2])
print("Entire Column : ", arr_2D[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific Element :  6
Entire Row :  [7 8 9]
Entire Row :  [7 8 9]
Entire Column :  [2 5 8]


## Sorting

In [87]:
unSorted = np.array([3,5,9,1,7,3,8])
print("Sorted Array:" , np.sort(unSorted))

unSorted_2D = np.array([[3,2],[1,2],[2,3]])
print("Sorted 2D Array by Column: \n", np.sort(unSorted_2D, axis=0))
print("Sorted 2D Array by Row: \n", np.sort(unSorted_2D, axis=1))

Sorted Array: [1 3 3 5 7 8 9]
Sorted 2D Array by Column: 
 [[1 2]
 [2 2]
 [3 3]]
Sorted 2D Array by Row: 
 [[2 3]
 [1 2]
 [2 3]]


## Filter

In [88]:
numbers = np.arange(1, 11)
evenNumbers = numbers[numbers%2 == 0]
print("Even numbers array : ", evenNumbers)

Even numbers array :  [ 2  4  6  8 10]


## Filter with Mask

In [89]:
mask = numbers > 5
print("Numbers greater than 5 : ", numbers[mask])

Numbers greater than 5 :  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [90]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result) # stores indices of array
print("numpy where :", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
numpy where : [ 6  7  8  9 10]


In [91]:
condition_arr = np.where(numbers>5, numbers*2, numbers)
condition_arr = np.where(numbers>5, "false", "true")
print(condition_arr)

['true' 'true' 'true' 'true' 'true' 'false' 'false' 'false' 'false'
 'false']


## Adding and Removing Data

In [92]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = arr1 + arr2
print(combined)

combined = arr1 * arr2
print(combined)

concatenatedArray = np.concatenate((arr1,arr2))
print(concatenatedArray) 

[5 7 9]
[ 4 10 18]
[1 2 3 4 5 6]


## Array Compatibility

In [93]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,2])

print("Compatibilty shapes : ", a.shape==b.shape)
print("Compatibilty shapes : ", a.shape==c.shape)

Compatibilty shapes :  True
Compatibilty shapes :  False


In [98]:
original = np.array([[1,2,3],[4,5,6]])
new_row = np.array([[4,7,2]])

withNewRow = np.vstack((original, new_row)) # adds new row
print(withNewRow)

new_col = np.array([[8,3], [3,4]])
withNewcol = np.hstack((original, new_col))
print(withNewcol)

[[1 2 3]
 [4 5 6]
 [4 7 2]]
[[1 2 3 8 3]
 [4 5 6 3 4]]


In [100]:
array = np.arange(6)
print(array)
deleted = np.delete(array, 2) # returns array after deletion
print(deleted)

[0 1 2 3 4 5]
[0 1 3 4 5]
