## Numpy Arrays

In [13]:
import numpy as np
import time

## Creating Array from List

In [7]:
arr_1D = np.array([1,2,3,4,5])
print("1D Array : ", arr_1D)

arr_2D = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("\n 2D Array : \n", arr_2D)

1D Array :  [1 2 3 4 5]

 2D Array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## List vs numpy Array

### Multiplication

In [9]:
mylist = [1,2,3]
print("List multiplied by 2 : ", mylist*2)

arr = np.array(mylist)
print("Numpy Array multiplied by 2 : ", arr*2)

List multiplied by 2 :  [1, 2, 3, 1, 2, 3]
Numpy Array multiplied by 2 :  [2 4 6]


In [17]:
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("List Operation time : ", time.time() - start)


start = time.time()
np_array = np.arange(1000000)*2
print("Numpy Operation time : ", time.time() - start)

List Operation time :  1.8524425029754639
Numpy Operation time :  0.010876893997192383


## Creating Array from Scratch

In [26]:
zeroes = np.zeros((3,4))
print("\n numpy Zeroes Array : \n", zeroes)

ones = np.ones((3,4))
print("\n numpy Zeroes Array : \n", ones)

full = np.full((3,4), 7)
print("\n numpy Full Array : \n", full)

random = np.random.random((3,4))
print("\n numpy Random Array : \n", random)

sequence = np.arange(0,20,2)
print("\n numpy Sequence Array : \n", sequence)



 numpy Zeroes Array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 numpy Zeroes Array : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 numpy Full Array : 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

 numpy Random Array : 
 [[0.99937314 0.29809109 0.9452549  0.59904569]
 [0.98768576 0.50899326 0.44402661 0.50533806]
 [0.78407754 0.45577025 0.93745441 0.43625989]]

 numpy Sequence Array : 
 [ 0  2  4  6  8 10 12 14 16 18]


## Vector, Matrix and Tensor

In [37]:
vector = np.array([1,2,3])
print("Vector : ", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("\nMatrix : \n", matrix)

tensor = np.array([[[1,2,3],[3,4,5]],
                   [[9,5,2],[2,5,0]]])
print("\nTensor : \n", tensor)

Vector :  [1 2 3]

Matrix : 
 [[1 2 3]
 [4 5 6]]

Tensor : 
 [[[1 2 3]
  [3 4 5]]

 [[9 5 2]
  [2 5 0]]]


2d array is matrix and if more than 2 matrix than all those arrays are tensor

## Arrayb Properties

In [40]:
arr = np.array([[1,2,3],
                [5,6,7]])
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Data Type: ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
Data Type:  int64


## Array Reshaping

In [53]:
arr = np.arange(24)
print("Original Array: ", arr)

reshapedArr = arr.reshape((3,8))
print("\nReshaped Array: \n", reshapedArr)

flattendArr = reshapedArr.flatten()
print("\n Flattend Array: ", flattendArr)

# ravel - return view instead of copy
raveledArr = reshapedArr.ravel() # returns original array
print("\n Raveled Array: ", raveledArr)

transposeArr = reshapedArr.T
print("\n Transposed Array Array: ", transposeArr)



Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Reshaped Array: 
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]

 Flattend Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

 Raveled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

 Transposed Array Array:  [[ 0  8 16]
 [ 1  9 17]
 [ 2 10 18]
 [ 3 11 19]
 [ 4 12 20]
 [ 5 13 21]
 [ 6 14 22]
 [ 7 15 23]]
